# Generated by Django 2.2 on 2019-06-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0010_auto_20190623_0841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
