# Generated by Django 2.2 on 2019-06-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190622_0904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
